### ISSUE TITLE
[Question] The formular in UpdaterWheel::preintegration_3D

### ISSUE THREAD

**Issue by qpc001** [rpng/MINS#17]
I don't understand why `p0_dot = R_Gto0.transpose() * v_hat;` but not `p0_dot = R_Gto0 * v_hat;`

```
  // k1 ================
  Vector4d dq_0 = {0, 0, 0, 1};
  Vector4d q0_dot = 0.5 * Omega(w_hat) * dq_0;
  Matrix3d R_Gto0 = quat_2_Rot(quat_multiply(dq_0, q_local));
  Vector3d p0_dot = R_Gto0.transpose() * v_hat;
```

Is it because of the quaternion is in JPL style?

**Comment by WoosikLee2510** [comment]
No, it is because ```v_hat``` is in the wheel frame, thus you need to multiply ```R_OtoG``` to convert it to global.

**Comment by WoosikLee2510** [comment]
No, ```R_GtoO``` is a rotation matrix. It has nothing to do with quaternions and representation type, i.e., JPL or Hamilton.

**Comment by WoosikLee2510** [comment]
Yes, it is because you are checking 'how to convert quaternions to rotation matrix' which should be related to quaternion representation. Eigen library assumes the quaternion is Hamilton and we use it JPL so there should be a difference when you convert it to a Rotation matrix. However, I am re-emphasizing, the rotation matrix should be the same if you convert JPL quat to Rot using JPL conversion and H. quat to Rot using H. conversion.

**Comment by WoosikLee2510** [comment]
To be precise, JPL does not need to transpose or conjugate (because it is just a vector), it's the corresponding rotation matrixes from JPL and H. to make them equal.
