### ISSUE TITLE
Initialization need platform to move and sometimes failed to init (drift)

### ISSUE THREAD

**Issue by se7oluti0n** [rpng/MINS#21]
Hi MINS maintainers,

First of all, thank you for great work and share it to the public community. I would like to apply MINS to the mobile robot application, I'm using stereo camera + IMU (Intel d435i) , but there are some issues of MINS that I want to ask:

1. Is there any way to make the system initialization while stay in one place, I assume that the VIO need platform to move to recover scale (in monocular camera), but in case of using stereo cameras, could I make the initiazation without moving?
2. Sometimes the initialization failed and pose got drifted. How could I prevent drifting?
3. I aware that CPU usage of MINS is much higher than that of Open-Vins ( in my PC, 150% CPU compare to 50% of OpenVINS). What cause the CPU usage higher?

**Comment by WoosikLee2510** [comment]
Hi, @se7oluti0n.
1. Yes, you can initialize the VIO without moving which is not included in MINS - as it is aiming for more sensor incorporation to handle such constrained case. You can refer to [OpenVINS](https://github.com/rpng/open_vins) how it can be done.

2. The quality of initialization using only IMU may highly depends on the threshold you set for initialization. Specifically, setting proper [imu_threshold](https://github.com/rpng/MINS/blob/master/mins/config/kaist/kaist_C/config_init.yaml#L5) is crucial so recommended to adjust the value.

3. I didn't do 1:1 comparison - it may due to larger default parameters for update, visualization, or size of the state. But you can surely play with the parameters to reduce CPU usage.

**Comment by se7oluti0n** [comment]
@WoosikLee2510 Thanks for answers. I will close the issues. Will feedback here if there is any update
