### ISSUE TITLE
Question about the feature representation

### ISSUE THREAD

**Issue by se7oluti0n** [rpng/MINS#23]
Dear MINS developer,

First of all, thanks for sharing your awesome work. According the report [Visual-Inertial Odometry on Resource-Constrained Systems](https://escholarship.org/content/qt4nn0j264/qt4nn0j264.pdf), compare between different feature representation,  the performance of the AHP and IDP parameterizations is significantly better than that of the XYZ parameterization. 

Currently, MINS only support `GLOBAL_3D` or `GLOBAL_FULL_INVERSE_DEPTH`, which I support it is XYZ parameterization in the paper. so the question is why MINS only support Global representation? Is it possible to use all feature representation (from Open-Vins) to integrate to MINS and improve the tracking stability? Thanks in advance.

**Comment by WoosikLee2510** [comment]
Hi, I am sorry for my delayed reply. Anchored feature representation can provide better performance, but it requires a solid camera pose (clone) to represent it. OpenVINS, for example, supports the anchored representation of features because it carries IMU poses at camera time. However, MINS carries IMU poses at an arbitrary time that makes the feature representation more inconsistent especially when you have inaccurate extrinsics and timeoffset calibration between the camera and the IMU. For these reasons, I decided not to support AHP in MINS. 
For IDP, yes - it might help. If you can make a pull request that would be great, otherwise, I will try to find time to implement it.
